import { expect, test, type Page } from '@playwright/test'

async function snapshot(page: Page) {
  return page.evaluate(async () => {
    const path = '/circuit/breadboard/src/store/useWorkbenchStore.ts'
    const { useWorkbenchStore } = await import(/* @vite-ignore */ path)
    const s = useWorkbenchStore.getState()
    return { annotations: s.annotations, document: s.document, dirty: s.dirty, past: s.past, annotationPast: s.annotationPast, closedContacts: s.closedContacts }
  })
}
async function point(page: Page, x: number, y: number) {
  const board = page.getByTestId('breadboard-canvas'), box = (await board.boundingBox())!
  const [offsetX, offsetY, scale] = (await board.getAttribute('data-board-transform'))!.split(',').map(Number)
  return { x: box.x + offsetX! + x * scale!, y: box.y + offsetY! + y * scale! }
}
async function drag(page: Page, from: [number, number], to: [number, number]) {
  const a = await point(page, ...from), b = await point(page, ...to)
  await page.mouse.move(a.x, a.y)
  await page.mouse.down()
  await page.mouse.move(b.x, b.y, { steps: 10 })
  await page.mouse.up()
}

async function expectRedInkAt(page: Page, x: number, y: number) {
  const screen = await point(page, x, y)
  await expect.poll(() => page.locator('.canvas-shell canvas').last().evaluate((element, p) => {
    const canvas = element as HTMLCanvasElement, rect = canvas.getBoundingClientRect()
    const rgba = canvas.getContext('2d')!.getImageData(Math.round((p.x - rect.x) * canvas.width / rect.width), Math.round((p.y - rect.y) * canvas.height / rect.height), 1, 1).data
    return rgba[0]! > 180 && rgba[1]! < 150 && rgba[3]! > 120
  }, screen)).toBe(true)
}

test('draws four kinds with separate history and keeps ink out of saved projects', async ({ page }, testInfo) => {
  await page.goto('')
  await page.waitForLoadState('networkidle')
  const before = await snapshot(page)
  const board = page.getByTestId('breadboard-canvas')
  const group = page.getByRole('group', { name: '标注与全屏', exact: true })
  expect(await group.locator('button').evaluateAll(nodes => nodes.map(n => n.getAttribute('data-testid')))).toEqual(['canvas-annotation-mode', 'canvas-fullscreen'])
  await page.getByTestId('canvas-annotation-mode').click()
  await expect(page.getByRole('button', { name: '画笔', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await drag(page, [220, 103], [400, 139])
  expect((await snapshot(page)).annotationPast).toHaveLength(1)
  await page.getByRole('button', { name: '蓝色', exact: true }).click()
  await page.getByLabel('标注粗细').selectOption('6')
  await page.getByRole('button', { name: '方框', exact: true }).click()
  await drag(page, [550, 220], [420, 120])
  await page.getByRole('button', { name: '箭头', exact: true }).click()
  await drag(page, [650, 240], [520, 160])
  await page.getByRole('button', { name: '文字', exact: true }).click()
  await page.getByLabel('标注字号').selectOption('32')
  const textPoint = await point(page, 250, 220)
  await page.mouse.click(textPoint.x, textPoint.y)
  const editor = page.getByRole('textbox', { name: '标注文字' })
  await editor.fill('电压 5V\n注意正负极')
  const transform = await board.getAttribute('data-board-transform')
  await page.mouse.wheel(0, -300)
  await expect(board).toHaveAttribute('data-board-transform', transform!)
  await editor.press('Control+Enter')
  await expect(board).toHaveAttribute('data-annotation-count', '4')
  const state = await snapshot(page)
  expect(state.annotations.map((a: { kind: string }) => a.kind)).toEqual(['pen', 'rectangle', 'arrow', 'text'])
  expect(state.annotations[0]).toMatchObject({ color: '#ef4444', strokeWidth: 3 })
  expect(state.annotations[1]).toMatchObject({ color: '#2563eb', strokeWidth: 6 })
  expect(state.annotations[3]).toMatchObject({ text: '电压 5V\n注意正负极', fontSize: 32 })
  expect(state.document).toEqual(before.document)
  expect(state.dirty).toBe(before.dirty)
  expect(state.past).toEqual(before.past)
  await page.getByRole('button', { name: '清空标注' }).click()
  await expect(board).toHaveAttribute('data-annotation-count', '0')
  await page.keyboard.press('Control+z')
  await expect(board).toHaveAttribute('data-annotation-count', '4')
  await page.keyboard.press('Control+Shift+z')
  await expect(board).toHaveAttribute('data-annotation-count', '0')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('annotations-dark.png') })
  await page.getByRole('button', { name: '切换到浅色模式' }).click()
  await page.screenshot({ path: testInfo.outputPath('annotations-light.png') })
  const toolbar = (await page.getByRole('toolbar', { name: '标注工具' }).boundingBox())!
  const bounds = (await board.boundingBox())!
  expect(toolbar.x).toBeGreaterThanOrEqual(bounds.x)
  expect(toolbar.x + toolbar.width).toBeLessThanOrEqual(bounds.x + bounds.width)
  await page.getByTestId('canvas-annotation-mode').click()
  await expect(page.getByTestId('annotation-surface')).toHaveCount(0)
  await expect(board).toHaveAttribute('data-annotation-count', '4')
  await page.reload()
  await expect(board).toHaveAttribute('data-annotation-count', '0')
})

test('isolates circuit actions, handles Escape priority and retains aligned ink through viewport changes', async ({ page }, testInfo) => {
  await page.goto('')
  await page.getByTestId('part-resistor').click()
  await drag(page, [216, 103], [396, 103])
  const original = await snapshot(page)
  await page.getByTestId('canvas-annotation-mode').click()
  await drag(page, [216, 103], [396, 103])
  await page.keyboard.press('Delete')
  await page.keyboard.press('Backspace')
  expect((await snapshot(page)).document.components).toEqual(original.document.components)
  await page.getByTestId('canvas-annotation-mode').click()
  const body = await point(page, 306, 103)
  await page.mouse.click(body.x, body.y)
  await expect(page.getByTestId('breadboard-canvas')).toHaveAttribute('data-selected-count', '1')
  await page.getByTestId('canvas-annotation-mode').click()
  await expectRedInkAt(page, 306, 103)
  const ink = (await snapshot(page)).annotations
  const board = page.getByTestId('breadboard-canvas')
  const beforeZoom = await board.getAttribute('data-board-transform')
  await page.mouse.move(body.x, body.y)
  await page.mouse.wheel(0, -100)
  await expect.poll(() => board.getAttribute('data-board-transform')).not.toBe(beforeZoom)
  await expectRedInkAt(page, 306, 103)
  const beforePan = await board.getAttribute('data-board-transform')
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(body.x + 40, body.y + 40)
  await page.mouse.up({ button: 'middle' })
  await expect.poll(() => board.getAttribute('data-board-transform')).not.toBe(beforePan)
  await expectRedInkAt(page, 306, 103)
  await page.getByTestId('canvas-fullscreen').click()
  await expect(board).toHaveAttribute('data-annotation-mode', 'true')
  expect((await snapshot(page)).annotations).toEqual(ink)
  await expectRedInkAt(page, 306, 103)
  await page.screenshot({ path: testInfo.outputPath('annotations-fullscreen.png') })
  const start = await point(page, 400, 240)
  await page.mouse.move(start.x, start.y)
  await page.mouse.down()
  await page.mouse.move(start.x + 50, start.y + 20)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(board).toHaveAttribute('data-annotation-count', '1')
  await expect(board).toHaveAttribute('data-annotation-mode', 'true')
  await page.keyboard.press('Escape')
  await expect(board).toHaveAttribute('data-annotation-mode', 'false')
  await expect(page.locator('.app-shell')).toHaveClass(/is-canvas-fullscreen/)
  await page.keyboard.press('Escape')
  await expect(page.locator('.app-shell')).not.toHaveClass(/is-canvas-fullscreen/)
  await page.getByTestId('canvas-annotation-mode').click()
  await page.getByRole('button', { name: '文字', exact: true }).click()
  const textPoint = await point(page, 450, 250)
  await page.mouse.click(textPoint.x, textPoint.y)
  await page.getByLabel('标注文字').fill('取消输入')
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('标注文字')).toHaveCount(0)
  await expect(board).toHaveAttribute('data-annotation-mode', 'true')
  await page.getByTestId('part-wire').click()
  await expect(board).toHaveAttribute('data-annotation-mode', 'false')
})

test('captures release outside the canvas, cancels touch strokes for pinch and resets on new project', async ({ page, context }) => {
  await page.goto('')
  await page.getByTestId('canvas-annotation-mode').click()
  const board = page.getByTestId('breadboard-canvas')
  const start = await point(page, 300, 200)
  await page.mouse.move(start.x, start.y)
  await page.mouse.down()
  await page.mouse.move(5, 150, { steps: 10 })
  await page.mouse.up()
  await expect(board).toHaveAttribute('data-annotation-count', '1')
  const cdp = await context.newCDPSession(page)
  const p1 = await point(page, 350, 230), p2 = await point(page, 650, 230)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...p1, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: p1.x + 10, y: p1.y, id: 1 }] })
  const transform = await board.getAttribute('data-board-transform')
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...p1, id: 1 }, { ...p2, id: 2 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: p1.x - 40, y: p1.y, id: 1 }, { x: p2.x + 40, y: p2.y, id: 2 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => board.getAttribute('data-board-transform')).not.toBe(transform)
  await expect(board).toHaveAttribute('data-annotation-count', '1')
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...p1, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] })
  await expect(board).toHaveAttribute('data-annotation-count', '1')
  await page.getByTitle('新建', { exact: true }).click()
  await expect(board).toHaveAttribute('data-annotation-count', '0')
  await expect(board).toHaveAttribute('data-annotation-mode', 'false')
})

test('supports dots and multiline text while ignoring blank and composing submissions', async ({ page }) => {
  await page.goto('')
  await page.getByTestId('canvas-annotation-mode').click()
  const p = await point(page, 320, 180), board = page.getByTestId('breadboard-canvas')
  await page.mouse.click(p.x, p.y)
  expect((await snapshot(page)).annotations[0].points).toHaveLength(2)
  await expectRedInkAt(page, 320, 180)
  await page.getByRole('button', { name: '文字', exact: true }).click()
  await page.mouse.click(p.x, p.y)
  const editor = page.getByLabel('标注文字')
  await editor.fill('   \n ')
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await expect(board).toHaveAttribute('data-annotation-count', '1')
  await page.mouse.click(p.x, p.y)
  await editor.fill('电压')
  await editor.dispatchEvent('compositionstart')
  await editor.dispatchEvent('keydown', { key: 'Enter', ctrlKey: true, isComposing: true, bubbles: true })
  await expect(editor).toBeVisible()
  await editor.dispatchEvent('keydown', { key: 'Escape', isComposing: true, bubbles: true })
  await expect(editor).toBeVisible()
  await editor.dispatchEvent('compositionend', { data: '电压' })
  await editor.press('Enter')
  await editor.pressSequentially('5V')
  await page.getByRole('button', { name: '完成', exact: true }).click()
  expect((await snapshot(page)).annotations[1].text).toBe('电压\n5V')
  await page.mouse.click(p.x, p.y)
  await editor.fill('未完成')
  await page.getByTestId('canvas-fullscreen').click()
  await expect(editor).toHaveCount(0)
  await expect(board).toHaveAttribute('data-annotation-count', '2')
  await expect(board).toHaveAttribute('data-annotation-mode', 'true')
})

test('does not press a momentary circuit button while drawing over it', async ({ page }) => {
  await page.goto('')
  await page.getByTestId('part-menu-switch').click()
  await page.getByTestId('part-switch-button').click()
  await drag(page, [216, 103], [252, 103])
  const button = (await snapshot(page)).document.components[0]
  const knob = await point(page, 234, 103)
  await page.getByTestId('canvas-annotation-mode').click()
  await page.mouse.move(knob.x, knob.y)
  await page.mouse.down()
  expect((await snapshot(page)).closedContacts[button.id]).toBeUndefined()
  await page.mouse.up()
  await page.getByTestId('canvas-annotation-mode').click()
  await page.mouse.move(knob.x, knob.y)
  await page.mouse.down()
  expect((await snapshot(page)).closedContacts[button.id]).toBe(true)
  await page.mouse.up()
  expect((await snapshot(page)).closedContacts[button.id]).toBeUndefined()
})

test('erases whole annotations with one undo per gesture and preserves overlapping shapes', async ({ page }, testInfo) => {
  await page.goto('')
  await page.getByTestId('canvas-annotation-mode').click()
  await drag(page, [260, 140], [400, 140])
  await drag(page, [260, 220], [400, 220])
  const before = await snapshot(page)
  const board = page.getByTestId('breadboard-canvas')
  const eraser = page.getByRole('button', { name: '橡皮擦', exact: true })
  await eraser.click()
  await expect(eraser).toHaveAttribute('aria-pressed', 'true')
  expect(await eraser.evaluate(node => node.nextElementSibling?.getAttribute('aria-label'))).toBe('清空标注')
  await page.screenshot({ path: testInfo.outputPath('annotation-eraser.png') })
  // Travel across both complete strokes; one undo restores both.
  await drag(page, [330, 100], [330, 250])
  await expect(board).toHaveAttribute('data-annotation-count', '0')
  expect((await snapshot(page)).annotationPast).toHaveLength(before.annotationPast.length + 1)
  expect((await snapshot(page)).document).toEqual(before.document)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  expect((await snapshot(page)).annotations).toEqual(before.annotations)
  // Blank areas don't create history entries, and hovering does not erase.
  const blank = await point(page, 650, 140)
  await page.mouse.click(blank.x, blank.y)
  const onStroke = await point(page, 330, 140)
  await page.mouse.move(onStroke.x, onStroke.y)
  expect((await snapshot(page)).annotations).toEqual(before.annotations)
  await page.mouse.down()
  await page.keyboard.press('Escape')
  await page.mouse.up()
  expect((await snapshot(page)).annotations).toEqual(before.annotations)
  await expect(board).toHaveAttribute('data-annotation-mode', 'true')
  // Rectangle hit testing follows its outline, not its empty interior.
  await page.getByRole('button', { name: '方框', exact: true }).click()
  await drag(page, [280, 130], [380, 230])
  await eraser.click()
  const middle = await point(page, 330, 180)
  await page.mouse.click(middle.x, middle.y)
  await expect(board).toHaveAttribute('data-annotation-count', '3')
  // Erase the outline where it overlaps a stroke: only the top rectangle goes.
  const crossing = await point(page, 280, 140)
  await page.mouse.click(crossing.x, crossing.y)
  expect((await snapshot(page)).annotations).toEqual(before.annotations)
  await page.getByTestId('canvas-fullscreen').click()
  const zoomed = await point(page, 330, 140)
  await page.mouse.click(zoomed.x, zoomed.y)
  expect((await snapshot(page)).annotations).toEqual([before.annotations[1]])
})

test('erases arrowheads, text and pen dots, and cancels touch erasing when pinching', async ({ page, context }) => {
  await page.goto('')
  await page.getByTestId('canvas-annotation-mode').click()
  const dot = await point(page, 300, 140)
  await page.mouse.click(dot.x, dot.y)
  await page.getByRole('button', { name: '箭头', exact: true }).click()
  await drag(page, [450, 140], [600, 140])
  await page.getByRole('button', { name: '文字', exact: true }).click()
  const text = await point(page, 300, 230)
  await page.mouse.click(text.x, text.y)
  await page.getByLabel('标注文字').fill('教学标注')
  await page.getByRole('button', { name: '完成', exact: true }).click()
  const before = await snapshot(page)
  const eraser = page.getByRole('button', { name: '橡皮擦', exact: true })
  await eraser.click()
  const board = page.getByTestId('breadboard-canvas')
  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...dot, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ ...dot, id: 1 }, { x: dot.x + 150, y: dot.y, id: 2 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  expect((await snapshot(page)).annotations).toEqual(before.annotations)
  await page.mouse.click(dot.x, dot.y)
  await expect(board).toHaveAttribute('data-annotation-count', '2')
  const head = await point(page, 594, 143)
  await page.mouse.click(head.x, head.y)
  await expect(board).toHaveAttribute('data-annotation-count', '1')
  await page.mouse.click(text.x + 4, text.y + 4)
  await expect(board).toHaveAttribute('data-annotation-count', '0')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  expect((await snapshot(page)).annotations[0].text).toBe('教学标注')
})
